### ISSUE TITLE
Calculation of Rank Freezing

### ISSUE THREAD

**Issue by agniv-the-marker** [afvillaverde/strike-goldd#14]
I'm on manjaro linux (kde plasma) and after fixing the slashes for the directories, I got this code to do the first step, but then it freezes after outputting "Computing Rank >>>." Is there any idea why this might be happening?

**Comment by afvillaverde** [comment]
Hi,
If the problem is complex and therefore computationally very expensive, rank calculation can demand a lot of memory. For large models it may get stuck. But without knowing more details about the problem you're trying to solve, I can only guess. If you share your model, and the options that you are using, I might be able to give more advice.

**Comment by agniv-the-marker** [comment]
Sure. I'm using [this](https://docs.google.com/document/d/1cFMgqbaRznNaJZzm2M0r9GMUnooZfAnKvZjGVovcf6k/edit) model and all default values, so it is decently large. Currently running on an old laptop so the memory might be an issue. Do you know about ways to run matlab in the cloud with more resources perhaps?

**Comment by agniv-the-marker** [comment]
Here it is as a zip file.

[notch.mat.zip](https://github.com/afvillaverde/strike-goldd/files/15111142/notch.mat.zip)

**Comment by afvillaverde** [comment]
I was able to run your example using the ProbObsTest algorithm (which is in fact the recommended default algorithm). To use it, just select the following in the options file:
`opts.algorithm = 2`
The advantage of this algorithm w.r.t. the previously recommended one (i.e. the 'FISPO' algorithm) is precisely that it is much more memory efficient. Hence it seldom gets stuck in the calculations.
It turns out that your model has 4 unidentifiable parameters. Below is the output produced by STRIKE-GOLDD for this model:

 -------------------------------- 
 >>> STRIKE-GOLDD toolbox 4.2.0 
 -------------------------------- 

 Analyzing the notch model with the probabilistic algorithm... 

 >>> The model contains:
 22 states:
 [Dll4_c1; Notch1_c1; Dll4_Notch1_c1; NICD_c1; Hes_c1; Jagged1_c1; Jag_Notch_c1; Notch_jagc2_c1; pR2_c1; V_c1; R2_c1; Dll4_c2; Notch1_c2; Dll4_Notch1_c2; NICD_c2; Hes_c2; Jagged1_c2; Jag_Notch_c2; Notch_jagc1_c2; pR2_c2; R2_c2; V_c2]
 5 outputs:
 [pR2_c1; R2_c1; NICD_c1/Notch1_c1; Hes_c1; NICD_c1]
 0 known inputs:
 
 0 unknown inputs:
 
 26 parameters:
 [kf_dllN; kp_R2; kdp_R2; kr_dllN; Km; kcat; kdeg_NICD; kdeg_Notch; kdeg_Dll4; kp_Dll; teta; kdeg_Hes1; Kp_Hes; tetaHe; kon_cis; kdeg_Jag; kr_jagNotch; kr_cis; kf_jagNotch; Kp_Jag; tetaJag; kdeg_pR2; kdeg_iR2; Gs; kform_Notch; kp]
 >>> Computations are done modulo: 1000003 

 >>> Current order of calculations: 
     4

     8

    16

    32

    48

    48



 ------------------------ 
 >>> RESULTS SUMMARY:
 ------------------------ 

 Observability-Identifiability matrix calculated in 2.826719e+03 seconds. 

 >>> The rank of the observability matrix is 46 
     transcendence degree of k(U,Y) --> k(U,Y,x,p) is 2 

 >>> The model is not FISPO:
 >>> These parameters are identifiable:
      [kf_dllN, kp_R2, kdp_R2, kr_dllN, Km, kdeg_NICD, kdeg_Notch, kdeg_Dll4, kp_Dll, teta, kdeg_Hes1, Kp_Hes, tetaHe, kon_cis, kdeg_Jag, kr_jagNotch, kr_cis, kf_jagNotch, Kp_Jag, tetaJag, kdeg_pR2, kform_Notch] 
 >>> These parameters are unidentifiable:
      [kcat, kdeg_iR2, Gs, kp] 
 >>> The model is observable.
     All its states are observable.
 >>> Matrix analyzed in 5.282110e+00 seconds. 

 Total execution time: 2.832001e+03 seconds. 
>>
