### ISSUE TITLE
Strike-goldd 3.0 fails for 'Vajda1989' on Matlab R2015a

### ISSUE THREAD

**Issue by vliviu** [afvillaverde/strike-goldd#4]
Due to the fact that in MATLAB R2015b (and before),  the toolbox code that uses a function called 'join', which was introduced in MATLAB R2016a. We shall come back with updates on this issue.
Error is:
Undefined function 'join' for input arguments of type 'cell'.
Error in STRIKE_GOLDD (line 42)
        nmf=join(mf(1:end-1),'/');
Error in AutoRepar (line 39)
    STRIKE_GOLDD(modelname,1);

**Comment by afvillaverde** [comment]
Dear @vliviu ,
Thanks for pointing out this issue. To solve it, we have modified STRIKE_GOLDD.m so that the 'join' function is no longer used. Instead, the new code uses 'strfind', which was introduced before R2006a. Thus, this fix should improve the backwards compatibility.
If you still encounter issues, let us know.
